#+LANGUAGE:    en
#+OPTIONS:     H:2 num:nil toc:nil \n:nil @:t ::t |:t ^:t f:t TeX:t


* CNFgen formula generator and tools

  This repository provides the command

  - =cnfgen= formula generator;

  and  the  following  python  scripts, designed  to  operate  from/to
  dimacs CNFs:

  - =cnfshuffle= random shuffler;

  - =cnftransform= apply litfing or substitution; 

  - =kthgraph2pebformula= make pebbling formula from a DAG.

  You  can get  a brief  help on  how to  use these  tools by  running
  =<program_name> --help= from the command line.

  Run =cnfgen --help= to get a list of the implemented formula families.
  To get  more specific information  on one  class of formula  use the
  command

  : cnfgen <formula_type> --help

  See the webpage of the project at http://massimolauria.github.io/cnfgen/

** Installation
   
   You can install CNFgen from  [[http://pypi.python.org][Python Package Index]], together with all
   its dependencies, typing either

   : easy_install [--user] cnfgen

   or

   : pip install  [--user] cnfgen

   Otherwise it  is possible to install from source using
    
   : python setup.py install [--user]

   The =--user= option  allows to install the package in  the user home
   directory. If you  do that please check that the  location where the
   command   line   utilities   are   installed   is   in   your   PATH
   environment variable.

** Contribution 

   Please contribute by sending pull requests. 


Copyright 2012–2015 © Massimo Lauria ([[mailto:lauria.massimo@gmail.com][lauria.massimo@gmail.com]])
